### PR TITLE
Major project refactoring changes

### PR DESCRIPTION
**Pull request by GnikDroy**
- [X] Started using the sq namespace
 - [X] Using C++ styled braces.
- [X] Added resource_manager, resource exception and animation classes.
- [X] Modified existing code to work with resource_manager class
- [X] modified makefile (will need to make it more robust) to work with new folder structure
- [X]  separated the implementation and source files
- [X] added build instructions in ReadMe also method to track all requirements for building (Meeting the requirements section in ReadMe)
- [X] fixed indentation issues.
- [X] added cmake building option as an alternative to the makefile.
- [X] changed variables/filenames/classes to use snake_case (not fixed for older classes). (Fixed in further update)
- [x] const correctness in some but not all functions. Newer code was written with this in mind so is slightly better.
 
Despite all this, no visible changes will be seen in the game. Everything should work exactly as it did before.

### CODE REVIEW

**Comment by TheClonerx** [comment]
Instead of having the header files in `./src/headers/`, wouldn't it be better if they where in `./headers/`?

**Comment by GnikDroy** [comment]
Some additional fixes
- [X] Refactored variables and functions so that they use the same naming convention.
- [X] Added Doxyfile for documentation generation using Doxygen
- [X] Added documentation for resource_exception, texture_manager, animation and utilities.
- [X] Modified README.md to include more details about the project
- [X] Included build instructions in README

**Comment by GnikDroy** [comment]
@TheClonerx It's fine both ways for me, so we can change it if we wish. Just wanted src to include all source and header files. I have worked with both folder formats previously. Is there any advantage of using the ./include one over ./src/include ?

**Comment by TheClonerx** [comment]
I just prefer using `./include`, seems more organized. Also, that's the common way of doing it.

**Comment by TheOnlyWalrus** [comment]
pushing to master?

**Comment by GnikDroy** [comment]
Okay @TheClonerx it seems fine to use ./include and since you guys are familiar with doing it this way, I am going with it. Done.

@TheOnlyWalrus Also, I think pushing to master right now is good. Since, this code changes the entire project without really changing/breaking anything. It is now easier and more maintainable to contribute and accept contributions.

**Comment by TheOnlyWalrus** [comment]
Ok I was just making sure the changes weren’t going to break the project

**Comment by pixelsharmana** [comment]
* Added const correctness
* K&R brace style
* camelCase
* Renamed fontT.png to font.png
* Deleted extra files
* Deleted duplicate files
* Deleted extra whitespace
* Other various improvements

**Pull request merged**
